### ISSUE TITLE
Save Game Advice

### ISSUE THREAD

**Issue by WispaTS2** [ts2/ts2#109]
I have been playing the game using the 0.7.9 download. Due to the bug stopping services working working correctly on X1 speed, I have downloaded the server master files and rebuilt the server file.

The simulation now works fine on the X1 speed but when I save the simulation to return later, it loads the track plan but doesn't load any trains, then when I press pause, the screen goes blank.

Any ideas anyone?

**Comment by hklang10** [comment]
Tested on linux, built from source.   

I have to perform the "open recent" activity twice before the saved game will load.
Here is what I see......
 
1. Select open recent, select saved game
2. Dialog "The server closed the connection to the simulation" press OK
3. Dialog repeated "The server closed the connection to the simulation" press OK
4. Shows a blank screen, no track plan
5. Repeat from 1. select open recent / saved game
6. Shows the track plan but no trains
7. Select pause to run simulation
8. Trains appear.

Can you confirm if the saved game loads correctly on the second attempt?

**Comment by npiganeau** [comment]
I confirm that I did not check the save/load game feature after switching to v0.7. So I'm not surprised it is buggy. Don't hesitate to push a PR

**Comment by WispaTS2** [comment]
I am running a Linux machine Mint 19.1 Tessa
Below is the dump from my terminal when I run the save game, from the 0.7.9 server rather than the one I built to fix the x1 bug.

You've lost me a bit on the 'push a PR' line, sorry. Hopefully the below will help with whatever the issue is.

qt5ct: using qt5ct plugin
en_GB
qt5ct: D-Bus global menu: no
INFO[03-06|19:17:23] Loading simulation                       file=/tmp/simulation.json
INFO[03-06|19:17:23] Simulation initializing                  module=simulation msgType=0
INFO[03-06|19:17:23] Starting server                          module=server
INFO[03-06|19:17:23] Hub starting...                          module=server submodule=hub
INFO[03-06|19:17:23] Simulation loaded                        sim="London Liverpool Street Station"
INFO[03-06|19:17:23] Starting HTTP                            module=server submodule=http address=0.0.0.0:22222
INFO[03-06|19:17:24] Registered client                        module=server connection=127.0.0.1:43842 clientType=client managerType=
INFO[03-06|19:17:50] Simulation started                       module=simulation
panic: runtime error: index out of range [0] with length 0

goroutine 34 [running]:
github.com/ts2/ts2-sim-server/simulation.(*Train).ApplicableAction(...)
	/home/npiganeau/Progs/ts2-sim-server/simulation/trains.go:504
github.com/ts2/ts2-sim-server/simulation.(*Train).updateSignalActions(0xc0000fc160)
	/home/npiganeau/Progs/ts2-sim-server/simulation/trains.go:366 +0xb26
github.com/ts2/ts2-sim-server/simulation.(*Train).advance(0xc0000fc160, 0x1dcd6500)
	/home/npiganeau/Progs/ts2-sim-server/simulation/trains.go:198 +0x66
github.com/ts2/ts2-sim-server/simulation.(*Simulation).updateTrains(0xc000001680)
	/home/npiganeau/Progs/ts2-sim-server/simulation/simulation.go:378 +0x10e
github.com/ts2/ts2-sim-server/simulation.(*Simulation).run(0xc000001680)
	/home/npiganeau/Progs/ts2-sim-server/simulation/simulation.go:306 +0x80
created by github.com/ts2/ts2-sim-server/simulation.(*Simulation).Start
	/home/npiganeau/Progs/ts2-sim-server/simulation/simulation.go:288 +0x73
WS Error Connection is already closed.
WS Closed
Traceback (most recent call last):
  File "/home/burt/Games/ts2-0.7.9/ts2/mainwindow.py", line 970, in onClosed
    mainWindow.simulationClose()
  File "/home/burt/Games/ts2-0.7.9/ts2/mainwindow.py", line 666, in simulationClose
    self.simulationDisconnect()
  File "/home/burt/Games/ts2-0.7.9/ts2/mainwindow.py", line 662, in simulationDisconnect
    self.webSocket.removeHandlers()
  File "/home/burt/Games/ts2-0.7.9/ts2/mainwindow.py", line 956, in removeHandlers
    self.sendRequest("server", "removeListener", params={"event": "%s" % eventName})
  File "/home/burt/Games/ts2-0.7.9/ts2/mainwindow.py", line 924, in sendRequest
    self.conn.send(msg)
  File "/usr/lib/python3/dist-packages/websocket/_app.py", line 120, in send
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

**Comment by hklang10** [comment]
Ah, ok, that's helpful - I was using "drain" to test, will try again with Liverpool Street.  (PR=Pull Request=software patch)

**Comment by hklang10** [comment]
This is being caused if the loaded game has trains which are currently moving.  

When a game is loaded from save, the status of the moving trains is not 100% recalculated.  It is crashing because internal calculation (t.signalActions) has not been done for the trains.

I have a workaround, but there are two other non-crashing issues I want to resolve also.

**Comment by WispaTS2** [comment]
Thanks for the update.

Based on the above, I tried it again, making sure that all trains were either stationary in a platform or at a red light when I saved the game. On a reload, the same error happened.

I'm still trying to get my head round all this 'Github speak', sorry.

I don't know the first thing about coding, but if there is anything else I can test drive for you, let me know.

**Comment by hklang10** [comment]
OK I have some work in progress at hklang10/iss48-partfix  https://github.com/ts2/ts2-sim-server/compare/master...hklang10:iss48-partfix.  This is a hack but should allow many but not all saved games to be loaded.

This is not a perfect fix - known issues:
1. Unexpected penalty minutes may happen - I know what is causing this but don't know why it is happening - I have made a partial fix/workaround but not for all situations.
2. Trains stopped at red signals with active routes to next signal - if the game was saved with active routes, trains stopped at red/danger signals will pass the signal and "crash" into the train ahead.
3. There may be some server panics when resuming games.  some saves have been tested and work OK but there may be other saves which panic.  Debug/traceback would be welcome for these.

The underlying issue is because the file structure for saved games does not save the internal state of the server 100%.  Unfortunately that means that problem 2. is not a simple fix.

If you are compiling from source, these changes will probably need to be put into a local src/github.com/ts2/ path.  As far as I know, go will only compile correctly from that path and will not compile correctly from a local src/github,com/hklang/ path.

**Comment by WispaTS2** [comment]
Sorry for the long delay in coming back to you, lots going on.

I've tried various things but I cannot get it to work at all, probably me doing something wrong though.

I'll keep trying though :)
