### ISSUE TITLE
Simulation bug: train stuck stopped at station, subsequent strange behavior

### ISSUE THREAD

**Issue by orwell96** [ts2/ts2#111]
Version: 0.7.9 (release)
System: Debian 10

While playing around with the Liverpool Street simulation today, I noticed a strange behavior: 
Train 2T01 (IIRC) stopped at Bethnal Green (the train list showed "Stopped at station"). Even multiple simulation minutes after its due departure, it was not departing, although the departure signal was green. The train appeared as standing at the left end of the track section, extending only about 3 on-screen millimeters to the right.

To resolve the issue, I tried cancelling and re-setting the route, which had no effect.
Selecting "Proceed with caution" had no effect either.

I then tried "Reset service". This caused the train to remain at its current location, but to show "Waiting at red signal" in the train list (although the signal was green). Train still did not move.

I then tried saving and reloading the simulation. On loading the simulation again, the following error was displayed and the simulation refused to load:
```
INFO[02-23|15:23:00] Simulation started                       module=simulation
panic: runtime error: index out of range [0] with length 0

goroutine 52 [running]:
github.com/ts2/ts2-sim-server/simulation.(*Train).ApplicableAction(...)
        /home/npiganeau/Progs/ts2-sim-server/simulation/trains.go:504
github.com/ts2/ts2-sim-server/simulation.(*Train).updateSignalActions(0xc0002bb1e0)
        /home/npiganeau/Progs/ts2-sim-server/simulation/trains.go:366 +0xb26
github.com/ts2/ts2-sim-server/simulation.(*Train).advance(0xc0002bb1e0, 0x1dcd6500)
        /home/npiganeau/Progs/ts2-sim-server/simulation/trains.go:198 +0x66
github.com/ts2/ts2-sim-server/simulation.(*Simulation).updateTrains(0xc00006e600)
        /home/npiganeau/Progs/ts2-sim-server/simulation/simulation.go:378 +0x10e
github.com/ts2/ts2-sim-server/simulation.(*Simulation).run(0xc00006e600)
        /home/npiganeau/Progs/ts2-sim-server/simulation/simulation.go:306 +0x80
created by github.com/ts2/ts2-sim-server/simulation.(*Simulation).Start
        /home/npiganeau/Progs/ts2-sim-server/simulation/simulation.go:288 +0x73
```

I have not tried to reproduce the bug so far. When it appears again, I'll try to collect more information on it and post it here.

Edit: here's the relevant save file:
[liverpool-1.zip](https://github.com/ts2/ts2/files/6031265/liverpool-1.zip)

**Comment by orwell96** [comment]
Reproduced again. In fact, it can be reproduced quite reliably. Train 12 (service 2T01) stops at Bethnal Green but doesn't depart.
Relevant JSON:
```
{
      "__type__": "Train",
      "trainId": "12",
      "serviceCode": "2T01",
      "trainTypeCode": "4/317",
      "status": 20,
      "speed": 0,
      "initialSpeed": 0,
      "trainHead": {
        "__type__": "Position",
        "trackItem": "472",
        "previousTI": "478",
        "positionOnTI": 199.96204264589556
      },
      "appearTime": "05:33:22",
      "initialDelay": 0,
      "nextPlaceIndex": 1,
      "stoppedTime": 0
    },
```
As it appears, stoppedTime is never counted up, so the train does never depart. Setting stoppedTime to 2000 makes the train depart instantly when loading and starting the simulation again.
Relevant line appears to be here: https://github.com/ts2/ts2-sim-server/blob/97df100b716b238486ea903c13e1aa3ae272112c/simulation/trains.go#L575 however I see nothing wrong with this code.

Seems like I have to set up a development environment myself to test this out.

**Comment by orwell96** [comment]
Oh, i see
82c3f04f was after the last release. So this bug is already fixed, and it is related to timefactor 1x
