### ISSUE TITLE
BUGS in Editor > Services 

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#68]
The ```Append new line``` button shows
```
Traceback (most recent call last):
  File "/home/ts2/ts2/ts2/editor/editorwindow.py", line 883, in appendServiceLineBtnClicked
    self.editor.addServiceLine(service, index)
  File "/home/ts2/ts2/ts2/editor/editor.py", line 816, in addServiceLine
    serviceLine.initialize(service)
  File "/home/ts2/ts2/ts2/trains/service.py", line 266, in initialize
    self.simulation = service.simulation
```

The ```Insert new line``` buttons shows
```
Traceback (most recent call last):
  File "/home/ts2/ts2/ts2/editor/editorwindow.py", line 892, in insertServiceLineBtnClicked
    if len(service.lines) != 0:
AttributeError: 'NoneType' object has no attribute 'lines'
```

Will try and investegate

**Comment by npiganeau** [comment]
Do you have the end of the trace for the append new line ?

Did you create + select a service before clicking on append/insert (not sure the buttons are disabled when it is not the case) ?

**Comment by pedromorgan** [comment]
Ahh just realised that I ad no service selected... ..

**Comment by pedromorgan** [comment]
Umm, what I want to do is enable/disable button based on selection, but `selectionChanged` event is an override function, so not sure how to get around..

**Comment by npiganeau** [comment]
Tried signal/slot ?

**Comment by pedromorgan** [comment]
Fixed in pedro-dev (probably)
