### ISSUE TITLE
simplejson 

### ISSUE THREAD

**Issue by LottieVixen** [ts2/ts2#85]
Simplejson also needed to be installed and this isn't mentioned in the README.md (perhaps it should be?)
Error given prior to it
```
$ python3 start-ts2.py
Traceback (most recent call last):
  File "start-ts2.py", line 44, in <module>
    import ts2.application
  File "/Users/charlotte/git/ts2/ts2/application.py", line 25, in <module>
    from ts2 import mainwindow
  File "/Users/charlotte/git/ts2/ts2/mainwindow.py", line 26, in <module>
    from ts2 import simulation, utils
  File "/Users/charlotte/git/ts2/ts2/simulation.py", line 24, in <module>
    import simplejson as json
ModuleNotFoundError: No module named 'simplejson'
```

installation of it on mac/*nix is simple
`pip3 install simplejson` 
you can also use `python3 -m pip install` in place of pip3

**Comment by pedromorgan** [comment]
thanks for the report.

**Comment by pedromorgan** [comment]
Assume fixed so closing
