### ISSUE TITLE
Editor crashes during scenery modification

### ISSUE THREAD

**Issue by Sharpe49** [ts2/ts2#94]
Editor crashes when editing a line item. If a place code that does not exist, this error occurs : 
Traceback (most recent call last):
  File "C:\Users\gniew\Desktop\ts2\ts2\scenery\helper.py", line 161, in setData
    setattr(ti, ti.properties[index.row()].name, value)
  File "C:\Users\gniew\Desktop\ts2\ts2\scenery\lineitem.py", line 138, in placeCode
    place = self.simulation.place(value)
  File "C:\Users\gniew\Desktop\ts2\ts2\editor\editor.py", line 482, in place
    raise KeyError("Unknown Place with code %s" % placeCode)
KeyError: 'Unknown Place with code f'
This kind of error should be caught and displayed to the user.

**Comment by npiganeau** [comment]
Fixed in master
